item {
  name: "BG"
  id: 0
  display_name: "BG"
}
item {
  name: "2431"
  id: 1
  display_name: "2431"
}
item {
  name: "3003"
  id: 2
  display_name: "3003"
}
item {
  name: "3005"
  id: 3
  display_name: "3005"
}
item {
  name: "3010"
  id: 4
  display_name: "3010"
}
item {
  name: "3020"
  id: 5
  display_name: "3020"
}
item {
  name: "3021"
  id: 6
  display_name: "3021"
}
item {
  name: "3022"
  id: 7
  display_name: "3022"
}
item {
  name: "3023"
  id: 8
  display_name: "3023"
}
item {
  name: "3024"
  id: 9
  display_name: "3024"
}
item {
  name: "3069"
  id: 10
  display_name: "3069"
}
item {
  name: "3070"
  id: 11
  display_name: "3070"
}
item {
  name: "3176"
  id: 12
  display_name: "3176"
}
item {
  name: "3622"
  id: 13
  display_name: "3622"
}
item {
  name: "3700"
  id: 14
  display_name: "3700"
}
item {
  name: "3710"
  id: 15
  display_name: "3710"
}
item {
  name: "3958"
  id: 16
  display_name: "3958"
}
item {
  name: "4150"
  id: 17
  display_name: "4150"
}
item {
  name: "4274"
  id: 18
  display_name: "4274"
}
item {
  name: "6141"
  id: 19
  display_name: "6141"
}
item {
  name: "11211"
  id: 20
  display_name: "11211"
}
item {
  name: "11476"
  id: 21
  display_name: "11476"
}
item {
  name: "11477"
  id: 22
  display_name: "11477"
}
item {
  name: "15068"
  id: 23
  display_name: "15068"
}
item {
  name: "15573"
  id: 24
  display_name: "15573"
}
item {
  name: "22885"
  id: 25
  display_name: "22885"
}
item {
  name: "24201"
  id: 26
  display_name: "24201"
}
item {
  name: "24246"
  id: 27
  display_name: "24246"
}
item {
  name: "25269"
  id: 28
  display_name: "25269"
}
item {
  name: "29119"
  id: 29
  display_name: "29119"
}
item {
  name: "29120"
  id: 30
  display_name: "29120"
}
item {
  name: "33909"
  id: 31
  display_name: "33909"
}
item {
  name: "35480"
  id: 32
  display_name: "35480"
}
item {
  name: "36840"
  id: 33
  display_name: "36840"
}
item {
  name: "47458"
  id: 34
  display_name: "47458"
}
item {
  name: "47905"
  id: 35
  display_name: "47905"
}
item {
  name: "85984"
  id: 36
  display_name: "85984"
}
item {
  name: "87079"
  id: 37
  display_name: "87079"
}
item {
  name: "87087"
  id: 38
  display_name: "87087"
}
item {
  name: "87580"
  id: 39
  display_name: "87580"
}
item {
  name: "93273"
  id: 40
  display_name: "93273"
}
item {
  name: "98138"
  id: 41
  display_name: "98138"
}
item {
  name: "99206"
  id: 42
  display_name: "99206"
}
