version: '3'


services:
  lego_cnn:
    build: .
    volumes:
      - ./:/tf
    ports:
      - 8080:8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
