apiVersion: "nuclio.io/v1beta1"
kind: "NuclioFunction"
metadata:
  name: brixilated-lego
  namespace: nuclio
spec:
  description: >
    Uses the inception model of the TensorFlow open-source machine-learning library to classify images.
    The function demonstrates advanced uses of nuclio with a custom base image, third-party Python packages,
    pre-loading data into function memory (the AI Model), structured logging, and exception handling.
  runtime: "python:3.9"
  handler: tensor:classify
  minReplicas: 1
  maxReplicas: 1
  build:
    baseImage: python:3.9-buster
    commands:
    - "apt-get update && apt-get install -y wget ffmpeg libsm6 libxext6"
    - "pip install requests tensorflow==2.5.0 Pillow cython matplotlib opencv-python h5py pydot pydot-ng scipy scikit-image imgaug pycocotools"
    - "pip install numpy==1.21.2"
    #- "mkdir -p /tmp/weights /tmp/model"
    - "git clone https://github.com/LilDataMonster/Lego-CNN.git lego_cnn"
    - "curl -s https://api.github.com/repos/LilDataMonster/Lego-CNN/releases/latest   | grep browser_download_url  | cut -d '\"' -f 4 | wget -O mask_rcnn_lego.h5 -i -"
    #- "wget http://download.tensorflow.org/models/image/imagenet/inception-2015-12-05.tgz"
    #- "tar -xzvf inception-2015-12-05.tgz -C /tmp/tfmodel"
    #- "rm inception-2015-12-05.tgz"
